import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import styled from 'styled-components'

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login Oka",
  description: "Generated by create flowbite react",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
        <ThemeModeScript />
      </head>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
